from pathlib import Path
import shutil
import datetime as dt
import markdown
import re

# ----- Paths & constants
ROOT = Path(__file__).parent.resolve()
DATA = ROOT / "data"
DOCS = ROOT / "docs"
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")  # only real days like 2025-10-13

# ----- Styles & HTML shells
STYLE = """
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji"; margin: 24px auto; max-width: 900px; padding: 0 16px; line-height: 1.6; }
  h1,h2,h3 { line-height: 1.25; }
  nav { margin: 16px 0 24px; }
  .muted { opacity: .7; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 8px 14px; }
  a { text-decoration: none; }
  a:hover { text-decoration: underline; }
  .card { border: 1px solid #4444; border-radius: 12px; padding: 12px 14px; }
  footer { margin: 48px 0 16px; font-size: 0.9em; }
</style>
"""

# NOTE: the All days link now passes ?all=1 so index.html will not redirect
HTML_SHELL = """<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
{style}
<body>
<nav><a href="../index.html?all=1">← All days</a></nav>
{content}
<footer class="muted">Updated {updated_utc} • <a href="https://github.com/{repo}">GitHub repo</a></footer>
</body>
</html>
"""

INDEX_SHELL = """<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Daily Knowledge Garden — Archive</title>
{style}
<body>
<h1>🌱 Daily Knowledge Garden — Archive</h1>
<p class="muted">Autonomous daily reports generated by GitHub Actions.</p>
{latest_block}
<h2>All Days</h2>
<div class="grid">
{links}
</div>
<footer class="muted">Updated {updated_utc} • <a href="https://github.com/{repo}">GitHub repo</a></footer>
</body>
</html>
"""

# ----- Helpers

def repo_slug() -> str:
    # Hardcode for your repo
    return "jakep84/Daily-Knowledge-Garden"

def get_day_dirs() -> list[Path]:
    """Return only folders named like YYYY-MM-DD, sorted ascending."""
    if not DATA.exists():
        return []
    return sorted(
        p for p in DATA.iterdir()
        if p.is_dir() and DATE_RE.match(p.name)
    )

def convert_md_to_html(md_text: str) -> str:
    return markdown.markdown(md_text, extensions=["extra", "tables", "sane_lists"])

# ----- Build functions

def build_day(day_dir: Path, repo: str):
    """Create docs/YYYY-MM-DD/index.html and copy assets so relative links work."""
    day = day_dir.name
    out_dir = DOCS / day
    out_dir.mkdir(parents=True, exist_ok=True)

    # Copy plots/ and images/ if present
    for sub in ["plots", "images"]:
        src = day_dir / sub
        dst = out_dir / sub
        if src.exists():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)

    # Convert report.md → index.html (skip if missing)
    report_md_path = day_dir / "report.md"
    if not report_md_path.exists():
        print(f"Skipping {day}: no report.md")
        return

    report_md = report_md_path.read_text(encoding="utf-8")
    report_html = convert_md_to_html(report_md)
    updated = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    html = HTML_SHELL.format(
        title=f"Daily Knowledge Garden — {day}",
        style=STYLE,
        content=report_html,
        updated_utc=updated,
        repo=repo
    )
    (out_dir / "index.html").write_text(html, encoding="utf-8")

def build_index(days: list[Path], repo: str):
    # Build the archive list
    links = [
        f'<a class="card" href="./{d.name}/"><strong>{d.name}</strong><br><span class="muted">Daily report</span></a>'
        for d in days
    ]
    links_html = "\n".join(links)

    latest_block = ""
    redirect_snippet = ""   # injected when a real latest exists
    if days:
        latest = days[-1].name  # newest day (sorted ascending)
        latest_block = f'<p><strong>Latest:</strong> <a href="./{latest}/">{latest}</a></p>'
        # Redirect ONLY if ?all=1 is NOT present
        redirect_snippet = (
            f'<script>if(!new URLSearchParams(location.search).has("all"))'
            f' location.replace("./{latest}/");</script>'
        )

    updated = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    html = INDEX_SHELL.format(
        style=STYLE, links=links_html, updated_utc=updated, repo=repo, latest_block=latest_block
    )
    if redirect_snippet:
        html = html.replace("<body>", f"<body>\n{redirect_snippet}\n")
    (DOCS / "index.html").write_text(html, encoding="utf-8")

# ----- Entry point

def main():
    DOCS.mkdir(exist_ok=True)
    days = get_day_dirs()
    repo = repo_slug()

    for d in days:
        build_day(d, repo)

    build_index(days, repo)
    print("Site built into /docs")

if __name__ == "__main__":
    main()
