name: Daily Garden

on:
  schedule:
    - cron: "0 9,15,21 * * *" # daily at 09:00 UTC
  workflow_dispatch: {} # allow manual runs

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # we'll push with a token below

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        run: python main.py

      - name: Build Pages site (docs/)
        run: |
          python site_build.py
          echo "Built docs/"

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: daily update $(date -u +'%Y-%m-%d')"
          else
            echo "No changes to commit."
          fi

      - name: Push
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          fi
